name: domestic_flight_app_flutter
description: A Flutter application for booking domestic flights.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  http: ^0.13.6
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  responsive_builder: ^0.4.0
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.2.1
  # Add other dependencies as needed
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
